# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  install_packages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        run: yarn install
        
  build:
    runs-on: ubuntu-latest
    needs: [install_packages]

    steps:
      - uses: actions/checkout@v3

      - name: Build Script
        run: yarn build
